/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2018-11-08 07:15:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_005fpure_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html;charset=UTF-8\">\r\n");
      out.write("\t\t<title>工作台</title>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/v2/yesui/ui/allfile.js?v=20180730\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"home/menutree.js\" defer=\"defer\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"home/navigation.js\" defer=\"defer\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"home/main.js\" defer=\"defer\"></script>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<div class=\"nav\"></div>\r\n");
      out.write("\t\t<!-- 主体 -->\r\n");
      out.write("\t\t<div class=\"main\">\r\n");
      out.write("\t\t\t<div class=\"mainLeft\"></div>\r\n");
      out.write("\t\t    <div class=\"mainMiddle\"></div>\r\n");
      out.write("\t\t    <div id=\"form\" class=\"mainRight\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t$(function () {\r\n");
      out.write("\t\t\t\tvar nav = $(\".nav\").navigation();\r\n");
      out.write("\t\t\t\tvar container = new YIUIContainer($(\"#form\"));\r\n");
      out.write("\t\t\t\tvar tree = $(\".mainLeft\").menuTree(container);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tvar place_w = parseInt($(\"#form\").css(\"padding-left\")) + parseInt($(\"#form\").css(\"padding-right\")) + parseInt($(\"#form\").css(\"margin-left\")) + parseInt($(\"#form\").css(\"margin-right\"));\r\n");
      out.write("\t\t\t    var resize = function() {\r\n");
      out.write("\t\t\t\t    var place_h = parseInt($(\"#form\").css(\"padding-top\")) + parseInt($(\"#form\").css(\"padding-bottom\")) + parseInt($(\"#form\").css(\"margin-top\")) + parseInt($(\"#form\").css(\"margin-bottom\"));\r\n");
      out.write("\t\t\t\t    $(\".mainRight\").width($(document.body).width() - $(\".mainLeft\").outerWidth() - $(\".mainMiddle\").outerWidth() - place_w);\r\n");
      out.write("\t\t\t\t    $(\".mainLeft,.mainMiddle,.main\").height($(document.body).height() - $('.nav').height());\r\n");
      out.write("\t\t\t\t    $(\".mainRight\").height($(document.body).height() - $('.nav').height() - place_h);\r\n");
      out.write("\t    \t\t\ttree.resetHeight();\r\n");
      out.write("\t    \t\t\tnav.resize();\r\n");
      out.write("\t\t\t    };\r\n");
      out.write("\t\t\t    resize();\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t    setTimeout(function() {\r\n");
      out.write("\t\t\t    \tnav.resize();\r\n");
      out.write("\t\t\t    }, 0);\r\n");
      out.write("\r\n");
      out.write("\t\t\t    //移动条\r\n");
      out.write("\t\t\t    var bool = false;\r\n");
      out.write("\t\t\t    $('.mainMiddle').mousedown(function (event) {\r\n");
      out.write("\t\t\t        bool = true;\r\n");
      out.write("\t\t\t    });\r\n");
      out.write("\t\t\t    $('body').mouseup(function () {\r\n");
      out.write("\t\t\t        bool = false;\r\n");
      out.write("\t\t\t    });\r\n");
      out.write("\t\t\t    $(\".main\").mousemove(function (event) {\r\n");
      out.write("\t\t\t        if (bool == true) {\r\n");
      out.write("\t\t\t            var x = event.pageX;\r\n");
      out.write("\t\t\t            if (x <= 175) {\r\n");
      out.write("\t\t\t                x = 175;\r\n");
      out.write("\t\t\t            }\r\n");
      out.write("\t\t\t            if (($(document.body).width() - x) < 175) {\r\n");
      out.write("\t\t\t                x = $(document.body).width() - 175;\r\n");
      out.write("\t\t\t            }\r\n");
      out.write("\t\t\t            $('.mainLeft').width(x).show();\r\n");
      out.write("\t\t\t            $('.mainMiddle').css({left: x});\r\n");
      out.write("\t\t\t            $('.mainLeft').width(x);\r\n");
      out.write("\t\t\t            var $s_btn = $('.mainLeft .searchBox .search');\r\n");
      out.write("\t\t\t            var $s_txt = $('.mainLeft .searchBox .searchtext');\r\n");
      out.write("\t\t\t            $s_txt.width(x - $s_btn.width() - 20);\r\n");
      out.write("\t\t\t            $('.mainRight').width($(document.body).width() - x - $(\".mainMiddle\").outerWidth() - place_w);\r\n");
      out.write("\t\t\t            $('.matchItems').width($('.searchtext').width());\r\n");
      out.write("\t\t\t            container.doLayout($(\".mainRight\").width(), $(\".mainRight\").height());\r\n");
      out.write("\t\t\t        }\r\n");
      out.write("\t\t\t    });\r\n");
      out.write("\t\t\t    $(window).resize(function () {\r\n");
      out.write("\t\t\t        resize();\r\n");
      out.write("\t\t\t        container.doLayout($(\".mainRight\").width(), $(\".mainRight\").height());\r\n");
      out.write("\t\t\t    });\r\n");
      out.write("\t\t\t\t// 关闭注销session,同步注销,否则请求可能发不出去\r\n");
      out.write("\t\t\t\t$(window).on('beforeunload',function(e){\r\n");
      out.write("\t\t\t\t\tvar n = window.event.screenX - window.screenLeft;\r\n");
      out.write("\t\t\t\t\tvar b = n > document.documentElement.scrollWidth - 20;\r\n");
      out.write("\t\t\t\t\tif(b && window.event.clientY < 0 || window.event.altKey) {\r\n");
      out.write("\t\t\t\t\t\tvar paras = {\r\n");
      out.write("\t\t\t\t\t\t\t\tasync:false\r\n");
      out.write("\t\t\t\t\t\t\t};\r\n");
      out.write("\t\t\t\t\t\tSvr.SvrMgr.doLogout(paras,function(){\r\n");
      out.write("\t\t\t\t\t\t\t$.cookie(\"clientID\", null);\r\n");
      out.write("\t\t\t\t\t\t\t$.cookie(\"oldURL\",null);\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
