/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2015-05-28 11:58:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html;charset=UTF-8\">\r\n");
      out.write("\t    <meta http-equiv=\"Content-Type\" content=\"application/x-javascript;charset=UTF-8\">\r\n");
      out.write("\t    <title>工作台</title>\r\n");
      out.write("        <!--css引用-->\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"yesui/ui/plugin/css/jquery-ui.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"yesui/ui/plugin/css/ui.jqgrid.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"yesui/ui/plugin/css/fullcalendar/fullcalendar.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"yesui/ui/plugin/css/jquery.ui.dict.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"yesui/ui/plugin/css/jquery.ui.listview.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"yesui/ui/plugin/css/jquery.ui.maskinput.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"yesui/ui/plugin/css/jquery.ui.menubar.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"yesui/ui/plugin/css/jquery.ui.toolbar.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"yesui/ui/plugin/css/jquery.ui.treeview.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"yesui/ui/plugin/css/default/jquery.treeTable.css\">\r\n");
      out.write("   \t\t<link rel=\"stylesheet\" href=\"yesui/ui/res/css/blue/main.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"yesui/ui/res/css/blue/corecolor.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"yesui/ui/res/css/blue/core.css\">\r\n");
      out.write("        <!-- \r\n");
      out.write("        <link rel=\"stylesheet\" href=\"yesui/ui/res/css/grey/main.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"yesui/ui/res/css/grey/corecolor.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"yesui/ui/res/css/grey/core.css\">\r\n");
      out.write("        \r\n");
      out.write("        <link rel=\"stylesheet\" href=\"yesui/ui/res/css/orange/core.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"yesui/ui/res/css/orange/main.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"yesui/ui/res/css/orange/corecolor.css\">\r\n");
      out.write("          -->\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"yesui/ui/res/css/login.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"yesui/ui/plugin/css/bootstrap/bootstrap.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"yesui/ui/plugin/css/datepicker/css/layout.css\" />\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"yesui/ui/plugin/css/datepicker/css/datepicker.css\"/>\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"yesui/ui/plugin/css/smartspin/smartspinner.css\"/>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"yesui/ui/plugin/css/modaldialog/css/jquery.modaldialog.css\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"yesui/ui/plugin/css/paginationjs/pagination.css\" />\r\n");
      out.write("\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/jquery/jquery-1.10.2.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/plugin/js/jquery.cookie.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/plugin/js/jquery.json-2.3.min.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/yes-ui.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/plugin/js/jqgrid/grid.locale-cn.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/plugin/js/jqgrid/jquery.jqGrid.src.js\"></script>\r\n");
      out.write("        <script type=\"text/javascript\" src=\"yesui/ui/plugin/js/ajaxfileupload.js\"></script>\r\n");
      out.write("        <script type=\"text/javascript\" src=\"yesui/ui/plugin/js/uuid.js\"></script>\r\n");
      out.write("\t     \r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/plugin/js/ui-extend/jquery.placeholder.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/plugin/js/ui-extend/jquery.ui.treeTable.js\"></script>\r\n");
      out.write("\r\n");
      out.write("        <script type=\"text/javascript\" src=\"yesui/base/jsext.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/base/jQueryExt.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/svr/svrmgr.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/svr/proxyhandler.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/svr/request.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/expr/parser.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/fun/basefun.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/vparser.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/form.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/formstack.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/componentmgr.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/component.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/yiuiconsts.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/control/menu.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/control/toolbar.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/control/treemenubar.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/control/control.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/control/databinding.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/control/button.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/control/buttongroup.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/control/dropdownbutton.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/control/splitbutton.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/control/calendar.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/control/checkbox.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/control/combobox.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/control/databinding.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/control/datepicker.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/control/dict.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/control/dicttree.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/control/dictview.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/control/grid.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/control/chart.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/control/hyperlink.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/control/imagelist.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/control/label.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/control/listview.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/control/numbereditor.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/control/image.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/control/radiobutton.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/control/texteditor.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/control/textarea.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/control/textbutton.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/control/statusbar.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/control/treeview.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/control/passwordeditor.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/control/userinfopane.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/control/tree.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/control/attachment.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/control/separator.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/layout/autolayout.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/layout/borderlayout.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/layout/columnlayout.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/layout/fluidcolumnlayout.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/layout/gridlayout.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/layout/tabslayout.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/layout/splitlayout.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/layout/flexflowlayout.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/layout/tablelayout.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/layout/fluidtablelayout.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/panel/panel.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/panel/borderlayoutpanel.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/panel/columnlayoutpanel.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/panel/flowlayoutpanel.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/panel/flexflowlayoutpanel.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/panel/fluidcolumnlayoutpanel.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/panel/gridlayoutpanel.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/panel/splitpanel.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/panel/tabpanel.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/panel/tabpanelex.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/panel/treepanel.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/panel/tabcontainer.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/panel/tabexcontainer.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/panel/stackcontainer.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/component/panel/fluidtablelayoutpanel.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/ui/plugin/js/flotr/lib/bean-min.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/ui/plugin/js/flotr/lib/underscore-min.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/ui/plugin/js/flotr/js/Flotr.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/ui/plugin/js/flotr/js/DefaultOptions.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/ui/plugin/js/flotr/js/Color.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/ui/plugin/js/flotr/js/Date.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/ui/plugin/js/flotr/js/DOM.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/ui/plugin/js/flotr/js/EventAdapter.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/ui/plugin/js/flotr/js/Text.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/ui/plugin/js/flotr/js/Graph.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/ui/plugin/js/flotr/js/Axis.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/ui/plugin/js/flotr/js/Series.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/ui/plugin/js/flotr/js/Series.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/ui/plugin/js/flotr/js/types/lines.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/ui/plugin/js/flotr/js/types/bars.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/ui/plugin/js/flotr/js/types/points.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/ui/plugin/js/flotr/js/types/pie.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/ui/plugin/js/flotr/js/types/candles.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/ui/plugin/js/flotr/js/types/markers.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/ui/plugin/js/flotr/js/types/radar.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/ui/plugin/js/flotr/js/types/bubbles.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/ui/plugin/js/flotr/js/types/gantt.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/ui/plugin/js/flotr/js/types/timeline.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/ui/plugin/js/flotr/js/plugins/download.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/ui/plugin/js/flotr/js/plugins/selection.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/ui/plugin/js/flotr/js/plugins/spreadsheet.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/ui/plugin/js/flotr/js/plugins/grid.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/ui/plugin/js/flotr/js/plugins/hit.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/ui/plugin/js/flotr/js/plugins/crosshair.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/ui/plugin/js/flotr/js/plugins/labels.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/ui/plugin/js/flotr/js/plugins/legend.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/ui/plugin/js/flotr/js/plugins/titles.js\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t   \t<script type=\"text/javascript\" src=\"yesui/ui/plugin/js/datepicker/js/datepicker.js\"></script>\r\n");
      out.write("    \t<script type=\"text/javascript\" src=\"yesui/ui/plugin/js/datepicker/js/eye.js\"></script>\r\n");
      out.write("    \t<script type=\"text/javascript\" src=\"yesui/ui/plugin/js/datepicker/js/utils.js\"></script>\r\n");
      out.write("    \t<script type=\"text/javascript\" src=\"yesui/ui/plugin/js/smartspin/smartspinner.js\"></script>\r\n");
      out.write("    \t\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/ui/plugin/js/modaldialog/js/modaldialog.js\"> </script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/ui/plugin/js/paginationjs/pagination.js\"> </script>\r\n");
      out.write("\t\t<!-- \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"yesui/resource/css/YESUI-all-debug.css\">\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/YESUI-all-debug.js\"></script>\r\n");
      out.write("\t    \r\n");
      out.write("\t\t -->\r\n");
      out.write("\t    <script type=\"text/javascript\">\r\n");
      out.write("\t    \t$(function(){\r\n");
      out.write("\t    \t\t//input\r\n");
      out.write("\t    \t\t$.cookie(\"clientID\", Math.uuidFast());\r\n");
      out.write("\t    \t\tSvr.SvrMgr.LoadLoginForm(\"#loginWindow\");\r\n");
      out.write("\t    \t})\r\n");
      out.write("\t    </script>\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<div class=\"container\">\t\r\n");
      out.write("\t\t\t<div class=\"mainbody\">\r\n");
      out.write("\t\t\t\t<div id=\"loginDiv\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logoBox\">\r\n");
      out.write("\t\t\t\t\t\t<p>欢迎登录<span>博科平台1</span></p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"logoText\"><p>账号和密码均不能为空</p></div>\r\n");
      out.write("\t\t\t\t\t<div id=\"loginWindow\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<p class=\"footer\">© 2015 上海博科资讯股份有限公司版权所有</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
