/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2015-02-04 02:21:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class workspace_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t    <meta http-equiv=\"Content-Type\" content=\"application/json;charset=UTF-8\">\r\n");
      out.write("\t    <title>工作台</title>\r\n");
      out.write("\t    <!--css引用--><!-- \r\n");
      out.write("\t    <link rel=\"stylesheet\" href=\"yesui/plugins/jquery/css/jquery-ui-1.10.4.custom.min.css\">  -->\r\n");
      out.write("\t    <link rel=\"stylesheet\" href=\"yesui/plugins/jquery/css/jquery-ui.css\"> \r\n");
      out.write("\t    <link rel=\"stylesheet\" href=\"yesui/plugins/jquery/css/ui.jqgrid.css\">\r\n");
      out.write("\t    <link rel=\"stylesheet\" href=\"yesui/plugins/jquery/fullcalendar/fullcalendar.css\">\r\n");
      out.write("\t    <link rel=\"stylesheet\" href=\"yesui/plugins/jquery/css/jquery.ui.dict.css\">\r\n");
      out.write("\t    <link rel=\"stylesheet\" href=\"yesui/plugins/jquery/css/jquery.ui.listview.css\">\r\n");
      out.write("\t    <link rel=\"stylesheet\" href=\"yesui/plugins/jquery/css/jquery.ui.maskinput.css\">\r\n");
      out.write("\t    <link rel=\"stylesheet\" href=\"yesui/plugins/jquery/css/jquery.ui.menubar.css\">\r\n");
      out.write("\t    <link rel=\"stylesheet\" href=\"yesui/plugins/jquery/css/jquery.ui.toolbar.css\">\r\n");
      out.write("\t    <link rel=\"stylesheet\" href=\"yesui/plugins/jquery/css/jquery.ui.treeview.css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"yesui/plugins/jquery/css/default/jquery.treeTable.css\">\r\n");
      out.write("\t    <link rel=\"stylesheet\" href=\"yesui/resources/css/core.css\">\r\n");
      out.write("\t    <link rel=\"stylesheet\" href=\"yesui/resources/css/treemenubar.css\">\r\n");
      out.write("\t    <link rel=\"stylesheet\" href=\"yesui/plugins/jquery/bootstrap/css/bootstrap.css\"> \r\n");
      out.write("   \t\t<link rel=\"stylesheet\" href=\"yesui/plugins/jquery/datepicker/css/layout.css\" />\r\n");
      out.write("   \t\t<link rel=\"stylesheet\" href=\"yesui/plugins/jquery/datepicker/css/datepicker.css\"/>\r\n");
      out.write("   \t\t<link rel=\"stylesheet\" href=\"yesui/plugins/jquery/smartspin/smartspinner.css\"/>\r\n");
      out.write("\t\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/plugins/jquery/jquery-1.10.2.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/plugins/jquery/jquery.json-2.3.min.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/plugins/jquery/jquery.cookie.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/yes-ui.js\"></script><!-- \r\n");
      out.write("\t    fullcalendar只有在特定页面下才需要，可以使用动态加载js\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/ui/jquery/fullcalendar/fullcalendar.js\"></script> -->\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/plugins/jquery/jqgrid/grid.locale-cn.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/plugins/jquery/jqgrid/jquery.jqGrid.src.js\"></script>\r\n");
      out.write("\t    <!-- \r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/plugins/jquery/jquery-ui-i18n.js\"></script> --><!-- \r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/plugins/jquery/jquery-ui-1.10.4.custom.js\"></script> --><!-- \r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/plugins/jquery/ui-extend/jquery.ui.dict.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/plugins/jquery/ui-extend/jquery.ui.listview.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/plugins/jquery/ui-extend/jquery.ui.maskinput.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/plugins/jquery/ui-extend/jquery.ui.texteditor.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/plugins/jquery/ui-extend/jquery.ui.treeview.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/plugins/jquery/ui-extend/jquery.ui.treemenubar.js\"></script> -->\r\n");
      out.write("\t     <!-- \r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/plugins/jquery/jquery-ui.js\"></script> -->\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/plugins/jquery/ui-extend/jquery.ui.treeTable.js\"></script> <!-- \r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/plugins/jquery/ui-extend/jquery.ui.menubar.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/plugins/jquery/ui-extend/jquery.ui.toolbar.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/plugins/jquery/ui-extend/jquery.ui.treeTable.js\"></script> \r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/plugins/jquery/ui-extend/jquery-ui-timepicker-addon.js\"></script> -->\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/plugins/jquery/ui-extend/jquery.clearable.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/plugins/jquery/ui-extend/jquery.placeholder.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/common/jQueryExt.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/common/jQueryUtils.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/common/formstack.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/parser/parser.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/service/servicemanager.js\"></script><!-- \r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/struct/document.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/struct/datatable/datatable.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/struct/datatable/metadata.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/struct/datatable/columninfo.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/struct/datatable/rowstate.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/struct/datatable/row.js\"></script> -->\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/form.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/componentmgr.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/component.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/menu.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/toolbar.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/treemenubar.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/control/control.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/control/databinding.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/control/button.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/control/buttongroup.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/control/dropdownbutton.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/control/splitbutton.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/control/calendar.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/control/checkbox.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/control/combobox.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/control/databinding.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/control/datepicker.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/control/dict.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/control/dicttree.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/control/grid.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/control/chart.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/control/hyperlink.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/control/imagelist.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/control/label.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/control/listview.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/control/numbereditor.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/control/picture.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/control/radiobutton.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/control/texteditor.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/control/textbutton.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/control/statusbar.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/control/treeview.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/control/passwordeditor.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/control/userinfopane.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/layout/autolayout.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/layout/borderlayout.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/layout/columnlayout.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/layout/fluidcolumnlayout.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/layout/gridlayout.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/layout/tabslayout.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/layout/splitlayout.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/layout/flexflowlayout.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/layout/tablelayout.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/layout/fluidtablelayout.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/panel/panel.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/panel/borderlayoutpanel.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/panel/columnlayoutpanel.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/panel/flowlayoutpanel.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/panel/flexflowlayoutpanel.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/panel/fluidcolumnlayoutpanel.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/panel/gridlayoutpanel.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/panel/splitpanel.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/panel/tabpanel.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/panel/tabpanelex.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/panel/treepanel.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/panel/tabcontainer.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/panel/tabexcontainer.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/panel/stackcontainer.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/panel/tree.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/panel/fluidtablelayoutpanel.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/source/ui/component/treemenubar.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/source/ui/component/control/controlEvent.js\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"yesui/plugins/jquery/bootstrap/js/dropdown.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("        <script type=\"text/javascript\" src=\"eventTest.js\"></script>\r\n");
      out.write("        \r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/plugins/jquery/flotr/lib/bean-min.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/plugins/jquery/flotr/lib/underscore-min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/plugins/jquery/flotr/js/Flotr.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/plugins/jquery/flotr/js/DefaultOptions.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/plugins/jquery/flotr/js/Color.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/plugins/jquery/flotr/js/Date.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/plugins/jquery/flotr/js/DOM.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/plugins/jquery/flotr/js/EventAdapter.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/plugins/jquery/flotr/js/Text.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/plugins/jquery/flotr/js/Graph.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/plugins/jquery/flotr/js/Axis.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/plugins/jquery/flotr/js/Series.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/plugins/jquery/flotr/js/Series.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/plugins/jquery/flotr/js/types/lines.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/plugins/jquery/flotr/js/types/bars.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/plugins/jquery/flotr/js/types/points.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/plugins/jquery/flotr/js/types/pie.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/plugins/jquery/flotr/js/types/candles.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/plugins/jquery/flotr/js/types/markers.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/plugins/jquery/flotr/js/types/radar.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/plugins/jquery/flotr/js/types/bubbles.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/plugins/jquery/flotr/js/types/gantt.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/plugins/jquery/flotr/js/types/timeline.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/plugins/jquery/flotr/js/plugins/download.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/plugins/jquery/flotr/js/plugins/selection.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/plugins/jquery/flotr/js/plugins/spreadsheet.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/plugins/jquery/flotr/js/plugins/grid.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/plugins/jquery/flotr/js/plugins/hit.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/plugins/jquery/flotr/js/plugins/crosshair.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/plugins/jquery/flotr/js/plugins/labels.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/plugins/jquery/flotr/js/plugins/legend.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/plugins/jquery/flotr/js/plugins/titles.js\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t   \t<script type=\"text/javascript\" src=\"yesui/plugins/jquery/datepicker/js/datepicker.js\"></script>\r\n");
      out.write("    \t<script type=\"text/javascript\" src=\"yesui/plugins/jquery/datepicker/js/eye.js\"></script>\r\n");
      out.write("    \t<script type=\"text/javascript\" src=\"yesui/plugins/jquery/datepicker/js/utils.js\"></script>\r\n");
      out.write("    \t<script type=\"text/javascript\" src=\"yesui/plugins/jquery/smartspin/smartspinner.js\"></script>\r\n");
      out.write("    \t\r\n");
      out.write("    \t\r\n");
      out.write("\t\t<link type=\"text/css\" rel=\"stylesheet\" href=\"yesui/plugins/jquery/modaldialog/css/jquery.modaldialog.css\" />\r\n");
      out.write("\t\t<script type=\"text/javascript\" language=\"JavaScript\" src=\"yesui/plugins/jquery/modaldialog/js/modaldialog.js\"> </script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"yesui/plugins/jquery/kkpager/src/kkpager.js\"></script>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"yesui/plugins/jquery/kkpager/src/kkpager_blue.css\" />\r\n");
      out.write("\t    \r\n");
      out.write("\t    <!-- \r\n");
      out.write("        <script type=\"text/javascript\" src=\"yesui/YESUI-all-debug.js\"></script>\r\n");
      out.write("         -->\r\n");
      out.write("\t    \r\n");
      out.write("\t    \r\n");
      out.write("\t    <script type=\"text/javascript\">\r\n");
      out.write("\t        $(function () {\r\n");
      out.write("\t\t\t\t//根据jsType类型引入不同包下得controlEvent.js文件\r\n");
      out.write("\t\t\t\t//jsImport(getJsType());\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar location_pathname = document.location.pathname;\r\n");
      out.write("\t\t\t\twhile (location_pathname.indexOf('/') == 0)\r\n");
      out.write("\t\t\t\t\tlocation_pathname = location_pathname.substr(1);\r\n");
      out.write("\t\t\t\tvar baseurl = unescape(location_pathname.substr(0));\r\n");
      out.write("\t\t\t\tvar service = baseurl.substring(0, baseurl.indexOf('/'));\r\n");
      out.write("\t        \tServiceManager.ServletURL=[window.location.protocol,'//',window.location.host,'/',service,'/','servlet'].join('');\r\n");
      out.write("\t        \tinitWidth(); \r\n");
      out.write("\t\t        ServiceManager.loadHomePage(\"#form\");\r\n");
      out.write("\t        });\r\n");
      out.write("\t        function initWidth() {\r\n");
      out.write("\t            var bodyWidth = (document.compatMode == 'BackCompat') ?\r\n");
      out.write("\t                    document.body.clientWidth : document.documentElement.clientWidth;\r\n");
      out.write("\t            var bodyHeight = (document.compatMode == 'BackCompat') ?\r\n");
      out.write("\t                    document.body.clientHeight : document.documentElement.clientHeight;\r\n");
      out.write("\t            $('#form').css('width', bodyWidth);\r\n");
      out.write("\t            $('#form').css('height', bodyHeight);\r\n");
      out.write("\t        }\r\n");
      out.write("\t       function resizeViewport() {\r\n");
      out.write("\t        \tinitWidth();\r\n");
      out.write("\t        \t\r\n");
      out.write("\t        \tvar panel = FormStack.formList[0].getRootPanel();\r\n");
      out.write("\t        \tpanel.setWidth($('#form').width());\r\n");
      out.write("\t        \tpanel.setHeight($('#form').height());\r\n");
      out.write("\t        \t  \r\n");
      out.write("\t        \tpanel.doLayout(panel.getWidth(), panel.getHeight());\r\n");
      out.write("\t        }\r\n");
      out.write("\t\t\t$(window).on('resize', resizeViewport); \r\n");
      out.write("\t    </script>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<div id=\"form\"></div>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
